### ISSUE TITLE
Is it too early to request MGBoxKit for Swift?

### ISSUE THREAD

**Issue by psi70y** [sobri909/MGBoxKit#125]
I know its too early.
Seriously, I hope you get a chance to port it across.  This is one of my favourite libraries.

**Comment by sobri909** [comment]
Those imports have been added to MGBox.h and MGScrollView.h in the 8.0.0 release. So Swift projects and projects without pch files should be happy now.

**Comment by sobri909** [comment]
Oh, but this issue isn't about that. heh. It's about Swift support in general.

Reopening, because I've got no idea whether MGBoxKit is playing nice in Swift in general yet.

**Comment by psi70y** [comment]
I am not up to the latest release and haven't tested it for a while, but I managed to get it working with swift 1.1 without major issues

**Comment by sobri909** [comment]
Great! Glad to hear that. I'll close this issue then.
