### ISSUE TITLE
Subclassing error with cocoapods

### ISSUE THREAD

**Issue by hmd183** [sobri909/MGBoxKit#133]
Hi,

I just switched from using MGBox to MGBoxKit using CocoaPods.
Everything is good except I'm unable to subclass MGBox.
After creating the subclass, XCode will throw me a bunch of errors for MGBlockWrapper and MGEvents.

Thanks,

**Comment by neilaur** [comment]
Hi,

I have the same problem on Xcode 6 (no pch file). Any news ?

By the way, thanks for your libs, very easy to use and customize.

**Comment by sobri909** [comment]
I'll be pushing out a new stable release shortly, so I'll make sure a sensible change for this gets into that.

**Comment by hmd183** [comment]
@neilaur While waiting for the new release you can fix it by importing UIKit and Foundation in the subclasses.

**Comment by neilaur** [comment]
Thanks for your replies @sobri909 @hmd183.

I tried to import UIKit and Foundation in my subclass, but i still have my errors (it's a test project with Xcode 6.1 and Cocoapods 0.36). I will try with my real project today or tomorrow which have an PCH file (project created with Xcode 5.1) and i keep in touch.

**Comment by sobri909** [comment]
I've added UIKit and Foundation imports to MGBox.h and MGScrollView.h in the 8.0.0 release, which just went out. Hopefully that resolves this problem.

I'll close for now. But if anyone's still having problems with missing imports, reply and we'll reopen and dig deeper.

**Comment by neilaur** [comment]
Thanks a lot ! Everything works :-)
