### ISSUE TITLE
Deprecated MGTableBox, MGTableBoxStyled and MGLineStyled.

### ISSUE THREAD

**Issue by kentdome** [sobri909/MGBoxKit#139]
Is there a sample app or notes how to best transition an existing app which makes use of "styled" objects i.e. MGTableBoxStyled to the new v8 format?

**Comment by sobri909** [comment]
No sample app, but the basic idea is to create subclasses of MGBox and MGLine and apply your own styling in the `setup` methods. For example a class `MyTableRow` which subclasses from `MGLine`, and has this `setup` method:

```objc
- (void)setup {
    [super setup];
    self.padding = UIEdgeInsetsMake(0, 8, 0, 8);
    self.font = [UIFont fontWithName:@"HelveticaNeue" size:12];
    self.textColor = UIColor.blackColor;
}
```

**Comment by sobri909** [comment]
You can also use the old pre v8 classes as subclassing examples. Just look at how they were doing it, and that should lead you to the right answers.

**Comment by kentdome** [comment]
Got it. Great library. Perfect thank you.
