### ISSUE TITLE
'Block' type is unknown

### ISSUE THREAD

**Issue by halpz** [sobri909/MGBoxKit#144]
I think you renamed the 'Block' type in MGBlockWrapper.h to MGBlock - 

this breaks MGLayoutBox

**Comment by sobri909** [comment]
Is there a line in MGLayoutBox that's still referencing `Block`? Shouldn't be :-/

**Comment by halpz** [comment]
I downloaded MGEvents and MGMushParser separetely because I hate cocoapods

**Comment by sobri909** [comment]
CocoaPods is the de facto standard, and MGBoxKit relies on it for pushing stable releases. If you're working outside of that framework, then the problems you encounter are yours to resolve. Good luck!

**Comment by ValentinKuznetsov** [comment]
Unfortunately, it does reference Block. (8.00)

**Comment by apvminsoe** [comment]
I am using Cocoapod but i am facing the same problem.

**Comment by eligreg** [comment]
This happened to me using Cocoapods:
`'MGBoxKit', '8.0.0'`
