### ISSUE TITLE
How can I enable elastic / bounce scrolling when there are only a few boxes in a MGScrollView

### ISSUE THREAD

**Issue by halpz** [sobri909/MGBoxKit#145]
when there are only a few items in the scrollview (not enough to fill the height of the screen) the bounce/elastic is disabled - how can I enable this?

**Comment by sobri909** [comment]
That's a feature of UIScrollView. There's a BOOL property for always bouncing.

**Comment by halpz** [comment]
I asked because setting .bounces = YES; doesn't seem to work

**Comment by halpz** [comment]
ahhh alwaysBounceVertical.   sorry
