### ISSUE TITLE
Re-ordering rows - can i put an MGScrollView into editing mode? like `moveRowAtIndexPath`?

### ISSUE THREAD

**Issue by halpz** [sobri909/MGBoxKit#146]
does it have a similar support?

**Comment by sobri909** [comment]
Do you mean a UI for allowing the user to reorder the rows? Or a way to programmatically do it yourself?

If the latter, then you can simply reorder the boxes in the `boxes` array, then call `layout` again, to update the presentation (or `layoutWithDuration:` to animate the change). 

If the former, then no, there's no built in UI for allowing the user to reorder the rows. You'd have to build that yourself.

**Comment by halpz** [comment]
Ahh I was looking the for former, I'm afraid - it would be a great feature! I use this Lib a lot

**Comment by sobri909** [comment]
Yeah I agree, it would. Unfortunately it's outside the project's scope, as far as spare time allows.
